name: Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install Dependencies, Generate Types, Build
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Run Tests
        run: yarn test
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}