name: On push to main

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - run: yarn run init
      - run: yarn test
        env:
          TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}

  # build_docker job  

  # deploy job