name: On pull request to main

on:
  pull_request:
    types:
      - ready_for_review
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/_build-and-test.yaml
    
  # build_docker job